# coding:utf-8
# for Debian 11

- name: delge環境に必要なパッケージをインストール。
  ansible.builtin.apt:
    name:
      - nfs-kernel-server

- name: マウントポイントのディレクトリを作成。
  file:
    path: /additionalssd
    state: directory

- name: SSDのマウントを確約する。
  mount:
    name: /additionalssd
    src: /dev/sdc1
    fstype: ext4
    opts: defaults
    state: mounted
