# coding:utf-8
# for Raspberry PI OS 11

- name: Webサーバと証明書更新ツールをインストール。
  ansible.builtin.apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx

- name: wiki用ドメインのリバースプロキシ用の設定とLet's EncryptのSSL証明書定期更新を有効に。
  include_tasks: tasks/auto_update_cert_domain_wiki.yml

- name: smarthome用ドメインのリバースプロキシ用の設定とLet's EncryptのSSL証明書定期更新を有効に。
  include_tasks: tasks/auto_update_cert_domain_smarthome.yml
