# coding:utf-8
# for Ubuntu on LocalMachine

- name: 別のパッケージ管理システム、
  apt:
    name: flatpak
    state: present

- name: InteliJ IDEA をFlatpack経由でインストール。
  community.general.flatpak:
    name: https://dl.flathub.org/repo/appstream/com.jetbrains.IntelliJ-IDEA-Community.flatpakref
    state: latest
