# site :opscode 
# 上記が古い、下に書き換えろ！という警告があるもので、従う。
source "https://supermarket.chef.io"

cookbook 'openssh'
cookbook 'user'

cookbook 'tomcat'

source "https://api.berkshelf.com"
cookbook 'apache2'

cookbook 'td-agent'

cookbook 'mysql'
