Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian10"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "4096"]
  end

  # Raidミラー環境の確認用に、HDDを2つ追加する。
  config.vm.provider :virtualbox do |p|
    disk_controller_name = 'IDE Controller' # 環境によって変わる。https://qiita.com/kjtanaka/items/8f3e92e029e46f826754#%E8%A3%9C%E8%B6%B3 のやり方で確認すること
    # portcountをディスクの数だけ増やす(例:2つ)
    p.customize [
      'storagectl', :id,
      '--name', disk_controller_name,
      '--portcount', 2]

    # Disk 02
    disk02_file = "./.tmp/sdb.vdi"
    unless File.exists?(disk02_file)
      p.customize [
        'createmedium', 'disk',
        '--filename', disk02_file,
        '--format', 'VDI',
        '--size', 1 * 1024]
    end
    p.customize [
      'storageattach', :id,
      '--storagectl', disk_controller_name,
      '--port', 1,
      '--device', 0,
      '--type', 'hdd',
      '--medium', disk02_file]
    # Disk 03
    disk03_file = "./.tmp/sdc.vdi"
    unless File.exists?(disk03_file)
      p.customize [
        'createmedium', 'disk',
        '--filename', disk03_file,
        '--format', 'VDI',
        '--size', 1 * 1024]
    end
    p.customize [
      'storageattach', :id,
      '--storagectl', disk_controller_name,
      '--port', 0,
      '--device', 1,
      '--type', 'hdd',
      '--medium', disk03_file]
    # Disk 04
    disk04_file = "./.tmp/sdd.vdi"
    unless File.exists?(disk04_file)
      p.customize [
        'createmedium', 'disk',
        '--filename', disk04_file,
        '--format', 'VDI',
        '--size', 1 * 1024]
    end
    p.customize [
      'storageattach', :id,
      '--storagectl', disk_controller_name,
      '--port', 1,
      '--device', 1,
      '--type', 'hdd',
      '--medium', disk04_file]
  end

  # IPを設定ファイルから読み込む。
  target_ip = ""
  File.foreach("./vagrant_hosts"){|line|
    target_ip = line.chomp()
  }
  config.vm.network "private_network", ip: target_ip

  # ssh設定
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines(".tmp/id_rsa.pub").first.strip
    s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      chmod 400 /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end
