# coding:utf-8
# for Debian(Raspberry PI OS 11) 11

- hosts: all
  become: yes
  become_user: root

  tasks:

  - block:

    - name: システム全更新。
      apt:
        update_cache: "yes"
        upgrade: "dist"

    - name: 不要なパッケージを削除。
      apt:
        name:
          - wireless-regdb
          - wireless-tools
          - nano
          - bluez-firmware
          - bluez
          - pi-bluetooth
          - alsa-utils
          - cifs-utils
          - dosfstools
          - nfs-common
          - ntfs-3g
          - python2
        state: absent
        purge: yes
        autoremove: yes

    - name: 必要なツールをインストール。
      apt:
        name:
          - tree
          - byobu
          - bind9
          - isc-dhcp-server

  - block:

    - name: ネットワーク設定ファイルを反映。
      copy: 
        src: resources/etc/dhcpcd.conf
        dest: /etc/dhcpcd.conf
        backup: yes

    - name: ホスト名設定。
      hostname:
        name: matsuichi

  - block:

    - name: NTP設定ファイルを反映。
      copy: 
        src: resources/etc/ntp.conf
        dest: /etc/ntp.conf
        backup: yes

    - name: NTPサービス再起動。
      systemd:
        name: ntp.service
        state: restarted
        daemon_reload: yes
        enabled: yes

