# coding:utf-8
# for Debian(Raspberry PI OS 11) 11

- hosts: all
  become: yes
  become_user: root

  vars:
    host_name: matsuichi

  tasks:

  - block:

    - name: システム全更新。
      apt:
        update_cache: "yes"
        upgrade: "dist"

    - name: 不要なパッケージを削除。
      apt:
        name:
          - wireless-regdb
          - wireless-tools
          - nano
          - bluez-firmware
          - bluez
          - cifs-utils
          - dosfstools
          - nfs-common
          - ntfs-3g
          - python2
        state: absent
        purge: yes
        autoremove: yes

    - name: 必要なツールをインストール。
      apt:
        name:
          - tree
          - byobu
          - ntp
          - bind9
          - isc-dhcp-server

  - block:

    - name: ネットワーク設定ファイルを反映。
      copy: 
        src: resources/etc/dhcpcd.conf
        dest: /etc/dhcpcd.conf
        backup: yes

    - name: raspi-config設定
      shell: |
        raspi-config nonint do_hostname {{ host_name }}
        raspi-config nonint do_change_locale ja_JP.UTF-8
        raspi-config nonint do_change_timezone Asia/Tokyo

    - name: ホスト名設定。
      hostname:
        name: "{{ host_name }}"

  - block:

    - name: NTP設定ファイルを反映。
      copy: 
        src: resources/etc/ntp.conf
        dest: /etc/ntp.conf
        backup: yes

    - name: NTPサービス再起動。
      systemd:
        name: ntp.service
        state: restarted
        daemon_reload: yes
        enabled: yes

  - block:

    - name: ゾーンファイルをコピー。
      copy:
        src: "{{ item }}"
        dest: /etc/bind/
        owner: root
        group: bind
        mode: "0644"
        backup: yes
      with_fileglob:
        - resources/etc/bind/*

    - name: bind9サービス再起動。
      systemd:
        name: named.service
        state: restarted
        daemon_reload: yes
        enabled: yes

  - block:

    - name: isc-dhcp-serverの設定をコピー。
      copy:
        src: resources/etc/default/isc-dhcp-server
        dest: /etc/default/isc-dhcp-server
        owner: root
        mode: "0644"
        backup: yes

    - name: dhcpdの設定をコピー。
      copy:
        src: resources/etc/dhcp/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf
        owner: root
        mode: "0644"
        backup: yes

    - name: dhcpサービス再起動。
      systemd:
        name: isc-dhcp-server.service
        state: restarted
        daemon_reload: yes
        enabled: yes

  - block:

    - name: DDNS反映スクリプトをコピー。
      copy:
        src: resources/usr/local/bin/ddns_sync.sh
        dest: /usr/local/bin/ddns_sync.sh
        mode: "0755"

    - name: DDNS反映スクリプトの設定ファイルをコピー。
      copy:
        src: resources/usr/local/etc/ddns_sync.conf.csv
        dest: /usr/local/etc/ddns_sync.conf.csv
        mode: "0644"

    - name: DDNS反映スクリプトのログローテート設定ファイルをコピー。
      copy:
        src: resources/etc/logrotate.d/ddns_sync
        dest: /etc/logrotate.d/ddns_sync
        mode: "0644"

    - name: DDNS反映スクリプトのcron設定。
      become: True
      cron:
        name: DDNS反映
        minute: "*/15"
        job: "/usr/local/bin/ddns_sync.sh"
        state: present
