#!/bin/bash

PORT=5554

ip=$(ip addr list eth0|grep "inet "|cut -d' ' -f6|cut -d/ -f1)
redir --laddr=$ip --lport=${PORT} --caddr=127.0.0.1 --cport=${PORT} &

echo "Starting emulator[$PORT]..."

# Set up and run emulator
# emulator64-${android_arch} -avd ${android_arch} -http-proxy "$http_proxy" -noaudio -no-window -gpu off -verbose3 -qemu -vnc :0
emulator64-arm -avd arm -no-audio -no-window -gpu off -verbose -port $PORT -qemu -vnc :0 &

# スリープとかかましたあとに、以下を実行。
wait-for-emulator
# 下の日本語化がしたかったが 「Systemがエラー 」とかになるので、一旦殺す。
# adb shell 'setprop persist.sys.locale ja; setprop persist.sys.timezone "Asia/Tokyo"; setprop persist.sys.country JP; setprop persist.sys.language ja; stop; start; sleep 5'
# wait-for-emulator
