# coding:utf-8
# for Debian 11

- hosts: all
  become: yes
  become_user: root

  tasks:

  - block:

    - name: システム全更新。
      ansible.builtin.apt:
        update_cache: "yes"
        upgrade: "dist"
        autoremove: true

    - name: 必要なツールをインストール。
      ansible.builtin.apt:
        name:
          - tree
          - byobu
          - vim
          - curl
          - ntp
          - nfs-common
          - sudo
          - parted
          - dnsutils
          - unzip
          - file

  - block:

    - name: ネットワーク設定ファイルを反映。
      copy: 
        src: resources/etc/network/interfaces
        dest: /etc/network/interfaces
        backup: yes

    - name: ホスト名設定。
      hostname:
        name: hachiro

  - block:

    - name: Swapをファイルで設定する。
      include_tasks: tasks/generate_and_mount_swapfile.yml

  - block: 

    - name: 本家からのdocker/docker-composeインストール。
      include_tasks: tasks/install_docker.yml

    - name: GROWIのdocker-composeからのインストール＆起動。
      include_tasks: tasks/install_growi_on_docker.yml
