# coding:utf-8
# for Debian 11

- hosts: all
  become: yes
  become_user: root

  tasks:

  - block:

    - name: システム全更新。
      apt:
        update_cache: "yes"
        upgrade: "dist"

    - name: 必要なツールをインストール。
      apt:
        name:
          - tree
          - byobu
          - vim
          - curl
          - ntp
          - nfs-common
          - sudo
          - parted
          - dnsutils

  - block:

    - name: ネットワーク設定ファイルを反映。
      copy: 
        src: resources/etc/network/interfaces
        dest: /etc/network/interfaces
        backup: yes

    - name: ホスト名設定。
      hostname:
        name: hachiro

  - block: 

    - name: 本家からのdocker/docker-composeインストール。
      include_tasks: tasks/install_docker.yml
