# coding:utf-8

# for Ubuntu 24.10 on LocalMachine

- hosts: all
  become: yes

  vars_files:
    - ./settings.yaml

  handlers:

  - name: tzdataのアップグレード。
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

  tasks:

  - name: ライブラリの全アップグレード
    include_tasks: ./tasks/all_upgrade.yaml

  - name: 日本語Limux”以外”を使う場合はonにする。
    include_tasks: ./tasks/japanize.yaml

  - name: Home下のディレクトリ名を英語に変更する。
    include_tasks: ./tasks/rename_home_template_dirs.yaml

  - name: 基本パッケージのインストール。
    include_tasks: ./tasks/install_basic_tools.yaml

  - name: 共通的なツールをインストール。
    include_tasks: ./tasks/install_common_tools.yaml
