# coding:utf-8

# for Ubuntu 24.10 on LocalMachine

- hosts: all
  become: yes

  vars_files:
    - ./settings.yaml

  handlers:

  - name: tzdataのアップグレード。
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

  tasks:

  - name: ライブラリの全アップグレード
    include_tasks: ./tasks/all_upgrade.yaml

  - name: 日本語Limux”以外”を使う場合はonにする。
    include_tasks: ./tasks/japanize.yaml

  - name: Home下のディレクトリ名を英語に変更する。
    include_tasks: ./tasks/rename_home_template_dirs.yaml

  - name: 基本パッケージのインストール。
    include_tasks: ./tasks/install_basic_tools.yaml

  - name: 共通的なツールをインストール。
    include_tasks: ./tasks/install_common_tools.yaml

  - name: Dropboxをnautilusで同期させる環境のセットアップ。
    include_tasks: ./tasks/setup_dropbox_client.yaml

  - name: ローカルでGoogleDriveをマウントできる環境のセットアップ。
    include_tasks: ./tasks/setup_googledrive_client.yaml

# TODO ResilioSyncを入れるか入れないかを判断、要るなら実装。

# TODO ascidocを入れるか入れないかを判断、要るなら実装。

  - name: ネットワーク系のコマンドをインストール。
    include_tasks: ./tasks/install_network_tools.yaml

  - name: 救援系のツールをインストール。
    include_tasks: ./tasks/install_rescure_tools.yaml

  # FIXME 一時的にコメントアウトするので、完成後は戻す事。
  # - name: モダンなフォントをセットアップ。
  #   include_tasks: ./tasks/setup_modan_fonts.yaml

# TODO vncserverを入れるか入れないかを判断、要るなら実装。

  - name: Webブラウザ等、Webに関するツールをセットアップ。
    include_tasks: ./tasks/setup_web_tools.yaml

  - name: メインユーザのgit環境をセットアップ。
    include_tasks: ./tasks/setup_git_command_for_mainuser.yaml

  - name: vim環境をセットアップ。
    include_tasks: ./tasks/setup_vim.yaml

  - name: マルチメディア再生系のソフトをインストール。
    include_tasks: ./tasks/install_multi_media.yaml
