# coding:utf-8

# for Ubuntu 24.10 on LocalMachine

- hosts: all
  become: yes

  vars_files:
    - ./settings.yaml

  handlers:

  - name: tzdataのアップグレード。
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

  tasks:

  - name: コミニュケーションツールをインストール。
    include_tasks: ./tasks/install_communication_tools.yaml
