# coding:utf-8

# for Ubuntu 24.10 on LocalMachine

- hosts: all
  become: yes

  vars_files:
    - ./settings.yaml

  handlers:

  - name: tzdataのアップグレード。
    command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

  tasks:

  - name: メインになるユーザーに関する設定を仕込む。
    include_tasks: ./tasks/config_main_user.yaml
