# coding:utf-8
# for Raspberry PI OS 11

- name: Webサーバと証明書更新ツールをインストール。
  ansible.builtin.apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx

- name: バーチャルドメイン設定ファイルの存在確認。
  stat:
    path: "/etc/nginx/sites-available/wiki.conf"
  register: domain_file

- name: バーチャルドメインの設定ファイルを追加。
  template:
    src: resources/etc/nginx/sites-available/wiki.conf
    dest: /etc/nginx/sites-available/wiki.conf
  when: not domain_file.stat.exists

- name: バーチャルドメインの設定ファイルを有効にする。
  file:
    src: /etc/nginx/sites-available/wiki.conf
    dest: /etc/nginx/sites-enabled/wiki.conf
    state: link

- name: デバッグ「ファイルが在ったか判定」の判定時期を確認。
  debug:
    msg: "wiki_server_domain_name:{{ wiki_server_domain_name }}"
