# coding:utf-8
# for Raspberry PI OS 11

- hosts: all
  become: yes
  become_user: root

  vars_files:
    - settings.yml

  tasks:

  - block:

    - name: システム全更新。
      apt:
        update_cache: "yes"
        upgrade: "dist"

    - name: 不要なパッケージを削除。
      apt:
        name:
          - wireless-regdb
          - wireless-tools
          - nano
          - bluez-firmware
          - bluez
          - cifs-utils
          - dosfstools
          - nfs-common
          - ntfs-3g
          - python2
        state: absent
        purge: yes
        autoremove: yes

    - name: 必要なツールをインストール。
      apt:
        name:
          - tree
          - byobu
          - curl

  - block:

    - name: ネットワーク設定ファイルを反映。
      copy: 
        src: resources/etc/dhcpcd.conf
        dest: /etc/dhcpcd.conf
        backup: yes

    - name: raspi-config設定
      shell: |
        raspi-config nonint do_hostname {{ host_name }}
        raspi-config nonint do_change_locale ja_JP.UTF-8
        raspi-config nonint do_change_timezone Asia/Tokyo

    - name: ホスト名設定。
      hostname:
        name: "{{ host_name }}"

  - block:

    - name: NTPクライアント設定ファイルを反映。
      copy: 
        src: resources/etc/systemd/timesyncd.conf
        dest: /etc/systemd/timesyncd.conf
        backup: yes

  - block:

    - name: リバースプロキシ用の設定とLet's EncryptのSSL証明書定期更新を有効に。
      include_tasks: tasks/enable_reverse_proxy_and_ssl.yml

  - block:

    - name: アップロード作業用ユーザを作成。
      user: 
        name: upload
        uid: 2000

    - name: アップロード作業用ユーザの公開鍵を登録する。
      authorized_key:
        user: upload
        state: present
        key: "{{ lookup('file', './resources/user/upload_key.pub') }}"
      become: yes

    - name: アップロード用の共有フォルダを作成。
      file:
        path: "/var/uploaded"
        state: directory
        owner: "root"
        group: "root"
        mode: "777"
